version: '3.8'
services:
  jmixai-postgres-vector:
    image: pgvector/pgvector:pg16-trixie
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vector_user -d mcp_docs -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  jmixai-reranker:
    image: mcp-reranker:latest
    ports:
      - "8000:8000"
